config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'todos#index'

  get 'users/index'

  resources :todos do
    member do
      put :switch, :update_todo
    end
      get :todo_active
      put :todo_active
  end

  resources :contacts, only: [:new, :create]
  # resources :contacts
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base

  attribute :name,      :validate => true
  attribute :message


  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
        :subject => "My Contact Form",
        :to => "anastasiya.kovaleva@dunice.net",
        :from => %("#{name}")
    }
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user

  validates :todo, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new()
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      redirect_to root_url , notice: 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message'
      # render :new
      redirect_to (:back), notice:'Cannot send message'
    end
  end

  def contact_params
    params.require(:contact).permit([:name, :message])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index

  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :set_todo!, only: [ :show, :edit, :update, :destroy, :switch, :update_todo, :todo_active, :index ]
  respond_to :json

  def index
    case params[:sort]
      when 'active'
        @todos = current_user.todos.where(todo_valid: true).order(:id)
      when 'inactive'
        @todos = current_user.todos.where(todo_valid: false).order(:id)
      else
        @todos = current_user.todos.order(:id)
    end
    respond_to do |format|
      format.html
      format.json { render json: @todos }
    end
  end

  def create
    @todo = current_user.todos.new(todo_params)
    if @todo.save
      render json: @todo
      flash[:notice] = 'Example has been created!'
    else
      render json: @todo.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @todo = Todo.find_by(id: params[:id])
    @todo.destroy if @todo
    author = current_user
    UserMailer.delete_todo(author).deliver
    respond_to do |format|
      # format.html
      format.json { render json: @todos }
    end
    flash[:success] = 'You delete your todo and you sent a message!'
  end

  def update
    @todo = assign_todo
    if @todos.update todo_params
      respond_to do |format|
        format.json { render json: @todo }
      end
    end
  end

  def update_todo
    @todo.update_attribute('todo', params[:todo])
    render json: @todo
  end

  def switch
    @todo.update_attribute('todo_valid', !@todo.todo_valid)
    render json: @todo
  end

  private

  def todo_params
    params.require(:todo).permit(:todo, :todo_valid, :user_id)
  end

  def set_todo!
    @todo = Todo.find_by(id: params[:id])
  end

  def assign_todo
    Todo.find params[:id]
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper

end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
      <div>
        <a href="#" data-dismiss="alert">×</a>
        <%= value %>
      </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div align="center conteiner col-md-1">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => ' center  col-md-6' } do |f| %>
      <%= f.input :name, :required => true %>
      <%= f.input :message, :as => :text, :required => true %>
      <div>
        </br>
        <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/layouts/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %> fade in">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <%= value %>
      </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div>
  <nav class="nav navbar-fixed-bottom" style="background-color: #000000">
     <span> Kovaleva Anastasiya Dunice Edge Company</span>
    <%= link_to 'Feedback', new_contact_path, class: "link-to-nav" %>
  </nav>
</div>

app/views/layouts/_header.html.erb
<div>
  <nav class="navbar navbar-light nav" style="background-color: #cc0909;">
    <%= link_to 'Add todo', todos_path, class: "link-to-nav" %>
    <%= link_to 'Edit profile', edit_user_registration_path, class: "link-to-nav" %>
    <%= link_to 'Sign out',  destroy_user_session_path,  class: "link-to-nav sign-header" , :method => :delete%>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRails</title>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_pack_tag 'webpack-bundle' %>
  </head>

    <%= render 'layouts/header'%>

  <div id="modal-holder"></div>

  <%= render 'layouts/flash_messages' %>

  <body>
    <%= yield %>

  </body>

    <%= render 'layouts/footer'%>

</html>

app/views/layouts/modal.html.erb
<div class="modal" id="mainModal" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="mainModalLabel">
          <%= yield :title if content_for? :title %>&nbsp;
        </h4>
      </div>

      <%= yield %>
    </div>
  </div>
</div>

app/views/todos/index.html.erb
<%= react_component("Todos", props: { todos: @todos}, prerender: false) %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>